---
     - name: Install Zabbix Repository and other packages needed by Ansible
       yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm state=installed
     - name: Insall zabbix agent
       yum: name=zabbix-agent state=installed
     - name: Config zabbix agent
       template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
     - name: Run zabbix agent
       service: name=zabbix-agent state=started enabled=yes

