---
# File: tasks/main.yml - Main tasks for Consul

- name: Create cluster groupings
  group_by: key={{ consul_node_role }}

- name: Install unzip
  yum: name=unzip state=present

- name: "Add Consul user"
  user: name=consul comment="Consul user" uid=1042 group=bin

- name: Download Consul
  get_url: "url={{ consul_zip_url }} dest=/tmp/{{ consul_centos_pkg }}"

- name: Install Consul
  unarchive: "copy=no src=/tmp/{{ consul_centos_pkg }} dest=/usr/local/bin/ owner={{ consul_user }} group={{ consul_group }} mode=0755"
  notify: remove consul archive

- name: Generate Consul key
  shell: PATH=/usr/local/bin:$PATH consul keygen
  register: consul_raw_key
  run_once: true

- name: Consul directories
  file: "dest=/opt/consul state=directory owner={{ consul_user }} group={{ consul_group}}"

- file: "dest=/opt/consul/ui state=directory owner={{ consul_user }} group={{ consul_group}}"

- file: "dest=/var/consul state=directory owner={{ consul_user }} group={{ consul_group}}"

- file: "dest=/var/log/consul state=directory owner={{ consul_user }} group={{ consul_group}}"

- file: "dest=/var/run/consul state=directory owner={{ consul_user }} group={{ consul_group}}"

- file: "dest=/etc/consul.d state=directory owner={{ consul_user }} group={{ consul_group}}"

- file: "dest=/etc/consul.d state=directory owner={{ consul_user }} group={{ consul_group}}"

- file: "dest=/etc/consul.d/bootstrap state=directory owner={{ consul_user }} group={{ consul_group}}"

- file: "dest=/etc/consul.d/server state=directory owner={{ consul_user }} group={{ consul_group}}"

- file: "dest=/etc/consul.d/client state=directory owner={{ consul_user }} group={{ consul_group}}"

- name: Initial Consul bootstrap configuration
  template: src=bootstrap_config.json.j2 dest={{ consul_config_path }}/bootstrap/config.json

- name: Initial Consul server configuration
  template: src=server_config.json.j2 dest={{ consul_config_path }}/server/config.json

- name: Initial Consul client configuration
  template: src=client_config.json.j2 dest={{ consul_config_path }}/client/config.json

- name: "Download Consul UI"
  get_url: url={{ consul_ui_url }} dest=/tmp/{{ consul_ui_pkg }} timeout=74

- name: "Install Consul UI"
  unarchive: src=/tmp/{{ consul_ui_pkg }} dest=/opt/consul/ui/ owner={{ consul_user }} group={{ consul_group }} mode=0755 copy=no

- name: SYSV init script
  template: src=consul_sysvinit.j2 dest=/etc/init.d/consul owner=root group=root mode=755
  when: not ansible_distribution == "Debian"

- name: systemd script
  template: src=consul_systemd.service.j2 dest=/lib/systemd/system/consul.service owner=root group=root mode=644
  when: ansible_distribution_major_version|int >= 7

- name: Start Consul
  service: name=consul state=started
