---
zabbix_ip_addr: "{{ ansible_eth0.ipv4.address }}"
zabbix_user: Admin
zabbix_user_password: zabbix
action: 'install'

database_name: 'zabbix'
path_from_copy: /usr/share/doc/zabbix-server-mysql-2.4.7/create/
path_to_files: /usr/share/doc/zabbix-server-mysql-2.4.7/create/
files_to_import: ["schema.sql","images.sql","data.sql"]

