---
- name: install haproxy
  yum: name=haproxy state=present

- name: copy ssl key
  copy: src=../files/domain.pem dest=/etc/ssl/domain.pem owner=root group=root mode=0644

- name: enable haproxy
  lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
  notify: start haproxy 

- name: deploy haproxy config
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy
