---

- name: Add "{{ database_user }}" User
  mysql_user: name={{ database_user }} password={{ database_password }} host={{ item }} priv=*.*:ALL,GRANT state=present
  with_items:
    - localhost
    - "%"

