---
- name: install haproxy
  yum:  name=haproxy state=present

- name: Turn Off Selinux
  selinux: state=disabled

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
  - restart haproxy

