---
# task file for MySQL role

- include: install.yml

- include: "{{ action }}.yml"
  when: action is defined

- include: replication.yml
  when: replicate is defined and replicate|lower() == 'yes'
