---
- name: Start MySQL Server
  service: name=mysql state=started enabled=yes

- name: Stop MySQL Server
  service: name=mysql state=stopped

- name: Restart MySQL Server
  service: name=mysql state=restarted

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: yes
  ignore_errors: yes

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
