#!/bin/bash
PATH="$PATH":/usr/bin:/usr/sbin:/bin:/sbin
ip tuntap add dev oms0 mode tap && ip link set oms0 up && ip link add name oms_br0 type bridge && ip link set oms0 master oms_br0 && ip link set oms_br0 up