---
- hosts: db1
  sudo: yes
  user: root

  roles:
      #    - { role: apache2, action: 'install' } # not needed now
    - { role: apache2, action: 'virtualhost', vhost_name: 'brun', vhost_dir: '/var/www/html/brun' }
    - { role: apache2, action: 'htaccess', username: 'admin', password: 'admin' }

